version: 2

jobs:
  build:
    branches:
      only:
        - /feature_circle_ci/
    docker:
      - image: "ubuntu:bionic-20191010"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install Git
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Display git version
          command: 'git --version'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build -- -j3'
      - run:
          name: Change dir to build
          command: 'cd build/ && ctest && cd ..'
